# Generated by Django 4.1.7 on 2025-07-11 10:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_alter_book_publication_date_borrowing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowing',
            unique_together={('user', 'book')},
        ),
    ]
